--- #YAML:1.0
name:               Net-RabbitMQ-Simple
version:            0.0006
abstract:           Simple way for RabbitMQ lib
author:
    - Thiago Berlitz Rondon <tbr@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Devel::Declare:       0.006
    ExtUtils::Install:    1.46
    ExtUtils::MakeMaker:  6.31
    Module::Build:        0.36
    Moose:                1.05
    MooseX::LazyRequire:  0.06
    MooseX::Method::Signatures:  0.36
    namespace::autoclean:  0.11
    Net::RabbitMQ:        0.1
    Test::More:           0.9
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
